//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Excavator.F1
{
    using System;
    using System.Collections.Generic;

    public partial class Activity_Group
    {
        public int Activity_ID { get; set; }

        public int Activity_Group_ID { get; set; }

        public Nullable<int> Activity_Super_Group_ID { get; set; }

        public string Activity_Group_Name { get; set; }

        public string Activity_Super_Group { get; set; }

        public string CheckinBalanceType { get; set; }
    }
}
