//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Excavator.F1
{
    using System;
    using System.Collections.Generic;

    public partial class Attribute
    {
        public string Attribute_Group_Name { get; set; }

        public string Attribute_Name { get; set; }

        public Nullable<int> Individual_Id { get; set; }

        public Nullable<System.DateTime> Start_Date { get; set; }

        public Nullable<System.DateTime> End_Date { get; set; }

        public string Comment { get; set; }

        public Nullable<int> Staff_Individual_ID { get; set; }
    }
}
