//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Excavator.F1
{
    using System;
    using System.Collections.Generic;

    public partial class Batch
    {
        public Nullable<int> BatchID { get; set; }

        public string BatchName { get; set; }

        public Nullable<System.DateTime> BatchDate { get; set; }

        public Nullable<decimal> BatchAmount { get; set; }
    }
}
