//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Excavator.F1
{
    using System;
    using System.Collections.Generic;

    public partial class Communication
    {
        public Nullable<int> Individual_ID { get; set; }

        public Nullable<int> Household_ID { get; set; }

        public string Communication_Type { get; set; }

        public string Communication_Value { get; set; }

        public Nullable<bool> Listed { get; set; }

        public string Communication_Comment { get; set; }

        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
    }
}
