//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Excavator.F1
{
    using System;
    using System.Collections.Generic;

    public partial class Company
    {
        public Nullable<int> Household_ID { get; set; }

        public string Household_Name { get; set; }

        public string Household_Sort_Name { get; set; }

        public Nullable<System.DateTime> Last_Activity_Date { get; set; }

        public string Old_ID { get; set; }

        public string CompanyType { get; set; }

        public string Contact_Name { get; set; }

        public Nullable<System.DateTime> Created_Date { get; set; }

        public Nullable<System.DateTime> Last_Updated_Date { get; set; }
    }
}
