//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Excavator.F1
{
    using System;
    using System.Collections.Generic;

    public partial class ContactFormData
    {
        public Nullable<int> ContactInstanceID { get; set; }

        public Nullable<int> ContactInstItemID { get; set; }

        public Nullable<System.DateTime> ContactActivityDate { get; set; }

        public Nullable<int> HouseholdID { get; set; }

        public Nullable<int> ContactIndividualID { get; set; }

        public Nullable<int> ContactItemIndividualID { get; set; }

        public Nullable<System.DateTime> ContactDatetime { get; set; }

        public string ContactNote { get; set; }

        public string ContactItemNote { get; set; }

        public string ContactFormName { get; set; }

        public string ContactItemName { get; set; }

        public string ContactItemTypeName { get; set; }

        public string ContactStatus { get; set; }

        public Nullable<int> ContactMinistryID { get; set; }

        public Nullable<int> RLCID { get; set; }

        public Nullable<int> ContactAssignedUserID { get; set; }

        public string ContactDispositionName { get; set; }

        public Nullable<bool> IsContactItemConfidential { get; set; }

        public Nullable<int> InitialContactCreatedByUserID { get; set; }

        public Nullable<int> ContactItemAssignedMinistryID { get; set; }

        public Nullable<int> ContactItemAssignedUserID { get; set; }

        public Nullable<System.DateTime> ContactFormLastUpdatedDate { get; set; }

        public Nullable<System.DateTime> ContactItemLastUpdatedDate { get; set; }
    }
}
