//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Excavator.F1
{
    using System;
    using System.Collections.Generic;

    public partial class GroupManager
    {
        public Nullable<int> GroupID { get; set; }

        public Nullable<int> IndividualID { get; set; }

        public Nullable<System.DateTime> CreatedDate { get; set; }

        public string AdminTypeName { get; set; }
    }
}
