//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Excavator.F1
{
    using System;
    using System.Collections.Generic;

    public partial class Groups
    {
        public string Group_Name { get; set; }

        public Nullable<int> Group_ID { get; set; }

        public Nullable<int> Individual_ID { get; set; }

        public Nullable<System.DateTime> Created_Date { get; set; }

        public string Group_Type_Name { get; set; }
    }
}
