//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Excavator.F1
{
    using System;
    using System.Collections.Generic;

    public partial class Individual_Household
    {
        public Nullable<int> Individual_ID { get; set; }

        public Nullable<int> Household_ID { get; set; }

        public string Household_Name { get; set; }

        public string Household_Position { get; set; }

        public string Last_Name { get; set; }

        public string First_Name { get; set; }

        public string Middle_Name { get; set; }

        public string Goes_By { get; set; }

        public string Former_Name { get; set; }

        public string Prefix { get; set; }

        public string Suffix { get; set; }

        public string Gender { get; set; }

        public Nullable<System.DateTime> Date_Of_Birth { get; set; }

        public string Marital_Status { get; set; }

        public Nullable<System.DateTime> First_Record { get; set; }

        public string Occupation_Description { get; set; }

        public string Employer { get; set; }

        public string School_Name { get; set; }

        public string Former_Church { get; set; }

        public string Status_Name { get; set; }

        public Nullable<System.DateTime> Status_Date { get; set; }

        public string Default_tag_comment { get; set; }

        public string OldFamNum { get; set; }

        public string OldIndividualID { get; set; }

        public string SubStatus_Name { get; set; }

        public string Bar_Code { get; set; }

        public string Member_Env_Code { get; set; }

        public string Status_Comment { get; set; }

        public string Title { get; set; }

        public string WeblinkLogin { get; set; }

        public string Denomination_Name { get; set; }

        public string Occupation_Name { get; set; }
    }
}
