//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Excavator.F1
{
    using System;
    using System.Collections.Generic;

    public partial class IndividualGiftedness
    {
        public Nullable<int> Individual_ID { get; set; }

        public Nullable<int> ConductedByIndividualID { get; set; }

        public Nullable<System.DateTime> AssessmentDate { get; set; }

        public Nullable<int> GiftProgramID { get; set; }

        public Nullable<int> GiftCategoryID { get; set; }

        public Nullable<int> GiftAttributeID { get; set; }

        public Nullable<int> Rank { get; set; }
    }
}
