//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Excavator.F1
{
    using System;
    using System.Collections.Generic;

    public partial class JobInformation
    {
        public Nullable<int> JobID { get; set; }

        public Nullable<System.DateTime> CreatedDate { get; set; }

        public Nullable<System.DateTime> LastUpdatedDate { get; set; }

        public string JobInformationName { get; set; }

        public Nullable<int> Sort { get; set; }

        public string JobInformationText { get; set; }
    }
}
