//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Excavator.F1
{
    using System;
    using System.Collections.Generic;

    public partial class RLC
    {
        public Nullable<int> RLC_ID { get; set; }

        public Nullable<int> Activity_ID { get; set; }

        public string RLC_Name { get; set; }

        public Nullable<int> Activity_Group_ID { get; set; }

        public Nullable<System.DateTime> Start_Age_Date { get; set; }

        public Nullable<System.DateTime> End_Age_Date { get; set; }

        public Nullable<bool> Is_Active { get; set; }

        public string Room_Code { get; set; }

        public string Room_Desc { get; set; }

        public string Room_Name { get; set; }

        public Nullable<int> Max_Capacity { get; set; }

        public string Building_Name { get; set; }
    }
}
