//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Excavator.F1
{
    using System;
    using System.Collections.Generic;

    public partial class Activity_Schedule
    {
        public string Activity_Time_Name { get; set; }

        public Nullable<System.DateTime> Activity_Start_Time { get; set; }

        public Nullable<System.DateTime> Activity_End_Time { get; set; }

        public Nullable<int> Activity_ID { get; set; }

        public Nullable<int> Activity_Schedule_ID { get; set; }
    }
}
