//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Excavator.F1
{
    using System;
    using System.Collections.Generic;

    public partial class ActivityMinistry
    {
        public Nullable<int> Ministry_ID { get; set; }

        public Nullable<int> Activity_ID { get; set; }

        public string Ministry_Name { get; set; }

        public string Activity_Name { get; set; }

        public Nullable<bool> Ministry_Active { get; set; }

        public Nullable<bool> Activity_Active { get; set; }
    }
}
