//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Excavator.F1
{
    using System;
    using System.Collections.Generic;

    public partial class Attendance
    {
        public Nullable<int> Individual_ID { get; set; }

        public Nullable<int> RLC_ID { get; set; }

        public Nullable<System.DateTime> Start_Date_Time { get; set; }

        public string Tag_Comment { get; set; }

        public string Tag_Code { get; set; }

        public string CheckedInAs { get; set; }

        public string BreakoutGroup_Name { get; set; }

        public Nullable<System.DateTime> Check_In_Time { get; set; }

        public Nullable<System.DateTime> Check_Out_Time { get; set; }

        public string Pager_Code { get; set; }

        public string Job_Title { get; set; }

        public string Checkin_Machine_Name { get; set; }
    }
}
