//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Excavator.F1
{
    using System;
    using System.Collections.Generic;

    public partial class Contribution
    {
        public Nullable<int> Individual_ID { get; set; }

        public Nullable<int> Household_ID { get; set; }

        public string Fund_Name { get; set; }

        public string Sub_Fund_Name { get; set; }

        public Nullable<System.DateTime> Received_Date { get; set; }

        public Nullable<decimal> Amount { get; set; }

        public string Check_Number { get; set; }

        public string Pledge_Drive_Name { get; set; }

        public string Memo { get; set; }

        public string Contribution_Type_Name { get; set; }

        public Nullable<decimal> Stated_Value { get; set; }

        public Nullable<decimal> True_Value { get; set; }

        public Nullable<decimal> Liquidation_cost { get; set; }

        public Nullable<int> ContributionID { get; set; }

        public Nullable<int> BatchID { get; set; }
    }
}
