//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Excavator.F1
{
    using System;
    using System.Collections.Generic;

    public partial class GiftednessProgram
    {
        public Nullable<int> GiftProgramID { get; set; }

        public Nullable<int> GiftCategoryID { get; set; }

        public Nullable<int> GiftAttributeID { get; set; }

        public string ProgramName { get; set; }

        public string ShortProgramName { get; set; }

        public string CategoryName { get; set; }

        public string AttributeName { get; set; }

        public Nullable<int> CategorySort { get; set; }

        public Nullable<int> AttributeSort { get; set; }

        public Nullable<bool> ProgramActive { get; set; }

        public Nullable<bool> CategoryActive { get; set; }

        public Nullable<bool> AttributeActive { get; set; }

        public Nullable<int> CategoryPercentage { get; set; }

        public Nullable<int> TotalJobAttributes { get; set; }

        public Nullable<int> MinJobAttributes { get; set; }

        public Nullable<int> JobAttributeWeight { get; set; }

        public Nullable<int> TotalIndividualAttributes { get; set; }

        public Nullable<int> MinIndividualAttributes { get; set; }

        public Nullable<int> IndividualAttributeWeight { get; set; }
    }
}
