//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Excavator.F1
{
    using System;
    using System.Collections.Generic;

    public partial class Group_Attendance
    {
        public Nullable<int> GroupID { get; set; }

        public Nullable<DateTime> StartDateTime { get; set; }

        public Nullable<DateTime> EndDateTime { get; set; }

        public Nullable<int> PresentCount { get; set; }

        public Nullable<int> AbsentCount { get; set; }

        public Nullable<int> TotalCount { get; set; }

        public Nullable<int> Met { get; set; }

        public string Comments { get; set; }

        public Nullable<int> IsPosted { get; set; }

        public Nullable<int> IsScheduled { get; set; }

        public Nullable<int> IndividualID { get; set; }

        public Nullable<DateTime> AttendanceDate { get; set; }

        public Nullable<int> IsPresent { get; set; }

        public Nullable<DateTime> CheckinDateTime { get; set; }

        public Nullable<DateTime> CheckoutDateTime { get; set; }

        public Nullable<DateTime> AttendanceCreatedDate { get; set; }

        public string GroupMemberType { get; set; }
    }
}
