//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Excavator.F1
{
    using System;
    using System.Collections.Generic;

    public partial class Staffing_Assignment
    {
        public string Activity_Time_Name { get; set; }

        public Nullable<System.DateTime> Activity_Start_Time { get; set; }

        public Nullable<System.DateTime> Activity_End_Time { get; set; }

        public Nullable<int> Individual_ID { get; set; }

        public string Job_Title { get; set; }

        public string Staffing_Schedule_Name { get; set; }

        public Nullable<bool> Is_Active { get; set; }

        public Nullable<int> Ministry_ID { get; set; }

        public Nullable<int> Activity_ID { get; set; }

        public Nullable<int> Activity_Group_ID { get; set; }

        public Nullable<int> RLC_ID { get; set; }

        public Nullable<int> Activity_Schedule_ID { get; set; }

        public Nullable<int> JobID { get; set; }
    }
}
