//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Excavator.F1
{
    using System;
    using System.Collections.Generic;

    public partial class Users
    {
        public Nullable<int> UserID { get; set; }

        public string UserLogin { get; set; }

        public string FirstName { get; set; }

        public string MiddleName { get; set; }

        public string LastName { get; set; }

        public string GoesBy { get; set; }

        public Nullable<bool> IsUserEnabled { get; set; }

        public string UserBio { get; set; }

        public Nullable<bool> IsPastor { get; set; }

        public Nullable<bool> IsStaff { get; set; }

        public string UserTitle { get; set; }

        public string UserPhone { get; set; }

        public string UserEmail { get; set; }

        public Nullable<int> LinkedIndividualID { get; set; }

        public Nullable<System.DateTime> UserCreatedDate { get; set; }

        public string DepartmentName { get; set; }
    }
}
